config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView
from users.views import CustomLoginView, register
from .views import custom_404


handler404 = custom_404

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='registration/logged_out.html'), name='logout'),
    path('register/', register, name='register'),
    path('menu/', include('menu.urls', namespace='menu')),
    path('users/', include('users.urls', namespace='users')),
    path('control-room/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'

urlpatterns = [
    path('', views.menu_categories, name='categories'),
    path('<str:category>/', views.menu_items, name='items'),
    path('<str:category>/<int:pk>/', views.menu_item_detail, 
         name='item_detail'),
]

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator, FileExtensionValidator
from django.core.exceptions import ValidationError
from django.utils.html import strip_tags
from PIL import Image


# =============================================================================
# Кастомные валидаторы и базовые модели / Custom validators and base models
# =============================================================================
def validate_image_size(image):
    """
    Ограничение размера загружаемого файла до 20 МБ
    Upload file size limit is 20 MB
    """
    limit_mb = 20
    limit = limit_mb * 1024 * 1024
    if image.size > limit:
        raise ValidationError(f'Максимальный размер файла - {limit_mb} MБ')


def validate_image_content(image):
    """
    Проверят, что загружаемый файл действительно является изображением
    Check that the file being uploaded is indeed an image
    """
    try:
        img = Image.open(image)
        img.verify()
        image.seek(0)
    except (IOError, SyntaxError, AttributeError):
        raise ValidationError('Недопустимый формат изображения')


class MenuItem(models.Model):
    """
    Абстрактная базовая модель для элементов меню
    Abstract base model for menu elements
    """
    name = models.CharField(
        'Название блюда',
        max_length=100,
        unique=True,
        help_text='Уникальное название блюда',
    )

    description = models.TextField(
        'Описание блюда',
        blank=True,
    )

    price = models.DecimalField(
        'Цена',
        max_digits=6,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0.01)],
        help_text='Цена должна быть положительной',
    )

    weight = models.PositiveBigIntegerField(
        'Вес (г)',
        default=0,
        validators=[MinValueValidator(1)],
        help_text='Вес блюда в граммах',
    )

    image = models.ImageField(
        'Изображение',
        upload_to='menu_images/',
        blank=True,
        null=True,
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
            validate_image_size,
            validate_image_content,
        ],
        help_text=('Загрузите изображение блюда (разрешены: .jpg, .jpeg, '
                   '.png; максимальный размер файла - 20 МБ)'),
    )

    calories = models.PositiveBigIntegerField(
        'Калорийность (ккал)',
        default=0,
        validators=[MinValueValidator(1)],
        help_text='Калорийность блюда в килокалориях',
    )

    proteins = models.DecimalField(
        'Белки (г)',
        max_digits=4,
        decimal_places=1,
        default=0,
        validators=[MinValueValidator(0)],
        help_text='Содержание белков в граммах',
    )

    fats = models.DecimalField(
        'Жиры (г)',
        max_digits=4,
        decimal_places=1,
        default=0,
        validators=[MinValueValidator(0)],
        help_text='Содержание жиров в граммах',
    )

    carbohydrates = models.DecimalField(
        'Углеводы (г)',
        max_digits=4,
        decimal_places=1,
        default=0,
        validators=[MinValueValidator(0)],
        help_text='Содержание углеводов в граммах',
    )


    def save(self, *args, **kwargs):
        """
        Автоматическое экранирование HTML перед сохранениием
        Automatically escape HTML before saving
        """
        self.name = strip_tags(self.name)
        self.description = strip_tags(self.description)
        super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        """
        Удаление модели и связанных с ней файлов изображений
        Deleting a model and its associated image files
        """
        if self.image:
            storage, path = self.image.storage, self.image.path
            storage.delete(path)
        super().delete(*args, **kwargs)


    class Meta:
        abstract = True
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
            models.Index(fields=['price']),
        ]


    def __str__(self):
        """
        Строковое представление модели
        String representation of the model
        """
        return f'{self.name} - {self.price}₽'


class Topping(models.Model):
    """
    Модель топпингов для блюд
    Model of toppings for dishes
    """
    name = models.CharField(
        'Название',
        max_length=100,
        unique=True,
        help_text='Уникальное название топпинга',
    )

    price_extra = models.DecimalField(
        'Доплата',
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0.01)],
        help_text='Дополнительная стоимость топпинга (неотрицательная)',
    )


    def save(self, *args, **kwargs):
        """
        Автоматическое экранировние HTML перед сохранением
        Automatically escape HTML before saving
        """
        self.name = strip_tags(self.name)
        super().save(*args, **kwargs)


    class Meta:
        ordering = ['name']
        verbose_name = 'топпинг'
        verbose_name_plural = 'Топпинги'


    def __str__(self):
        """
        Строковое представление модели
        String representation of the model
        """
        if self.price_extra:
            extra = f' (+{self.price_extra}₽)'
        else:
            extra = ''
        return f'{self.name}{extra}'


class BaseToppingRelation(models.Model):
    """
    Абстрактная модель связи блюда с топпингами
    Abstract model of the relationship between a dish and toppings
    """
    topping = models.ForeignKey(Topping, verbose_name='Топпинг',
                                on_delete=models.CASCADE)


    class Meta:
        abstract = True
        ordering = ['topping__name']


    def __str__(self):
        """
        Строковое представление модели
        String representation of the model
        """
        if hasattr(self, 'item'):
            return f'{self.item.name} + {self.topping.name}'
        return f'Топпинг: {self.topping.name}'


# =============================================================================
# Модели блюд / Models of dishes
# =============================================================================
class Pizza(MenuItem):
    class Meta:
        verbose_name = 'пиццу'
        verbose_name_plural = 'Пиццы'


class Burger(MenuItem):
    class Meta:
        verbose_name = 'бургер'
        verbose_name_plural = 'Бургеры'


class Snack(MenuItem):
    class Meta:
        verbose_name = 'снэк'
        verbose_name_plural = 'Снэки'


class Salad(MenuItem):
    class Meta:
        verbose_name = 'салат'
        verbose_name_plural = 'Салаты'


class Dessert(MenuItem):
    class Meta:
        verbose_name = 'десерт'
        verbose_name_plural = 'Десерты'


class Drink(MenuItem):
    class Meta:
        verbose_name = 'напиток'
        verbose_name_plural = 'Напитки'


# =============================================================================
# Модели связей блюд и топпингов / Models of relationships between dishes
# and toppings
# =============================================================================
class PizzaTopping(BaseToppingRelation):
    item = models.ForeignKey(Pizza, related_name='toppings',
                             verbose_name='Пицца', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг пиццы'
        verbose_name_plural = 'Топпинги пицц'


class BurgerTopping(BaseToppingRelation):
    item = models.ForeignKey(Burger, related_name='toppings',
                             verbose_name='Бургер', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг бургера'
        verbose_name_plural = 'Топпинги бургеров'


class SnackTopping(BaseToppingRelation):
    item = models.ForeignKey(Snack, related_name='toppings',
                             verbose_name='Снэк', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг снэка'
        verbose_name_plural = 'Топпинги снэков'


class SaladTopping(BaseToppingRelation):
    item = models.ForeignKey(Salad, related_name='toppings',
                             verbose_name='Салат', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг салата'
        verbose_name_plural = 'Топпинги салатов'


class DessertTopping(BaseToppingRelation):
    item = models.ForeignKey(Dessert, related_name='toppings',
                             verbose_name='Десерт', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг десерта'
        verbose_name_plural = 'Топпинги десертов'


class DrinkTopping(BaseToppingRelation):
    item = models.ForeignKey(Drink, related_name='toppings',
                             verbose_name='Напиток', on_delete=models.CASCADE)


    class Meta:
        unique_together = ('item', 'topping')
        verbose_name = 'топпинг напитка'
        verbose_name_plural = 'Топпинги напитков'

menu/views.py
from django.shortcuts import render, get_object_or_404
from .models import (Pizza, Burger, Snack, Salad, Dessert, Drink,
                     PizzaTopping, BurgerTopping, SnackTopping, SaladTopping,
                     DessertTopping, DrinkTopping)


CATEGORY_CONFIG = {
    'pizza': {'model': Pizza, 'name': 'Пицца', 'icon': '🍕',
                'topping_model': PizzaTopping},
    'burger': {'model': Burger, 'name': 'Бургеры', 'icon': '🍔',
                'topping_model': BurgerTopping},
    'snack': {'model': Snack, 'name': 'Снэки', 'icon': '🍟',
                'topping_model': SnackTopping},
    'salad': {'model': Salad, 'name': 'Салаты', 'icon': '🥗',
                'topping_model': SaladTopping},
    'dessert': {'model': Dessert, 'name': 'Десерты', 'icon': '🍰',
                'topping_model': DessertTopping},
    'drink': {'model': Drink, 'name': 'Напитки', 'icon': '🥤',
                'topping_model': DrinkTopping},
}


def menu_categories(request):
    """
    Представление страницы категорий меню
    View of the menu categories page
    """
    categories = []
    for url, config in CATEGORY_CONFIG.items():
        categories.append({
            'name': config['name'],
            'url': url,
            'count': config['model'].objects.count(),
            'icon': config['icon']
        })

    context = {
        'categories': categories,
        'title': 'Меню Animatronic Pizzeria',      
    }
    return render(request, 'menu/categories.html', context)


def menu_items(request, category):
    """
    Представление страницы списка блюд в категории
    View of the list page of dishes in a category
    """
    config = CATEGORY_CONFIG.get(category)
    if not config:
        return render(request, '404.html', status=404)

    items = config['model'].objects.all()
    category_name = config['name']

    context = {
        'items': items,
        'category': category,
        'category_name': category_name,
        'title': f'{category_name} | Animatronic Pizzeria',
    }
    return render(request, 'menu/items.html', context)


def menu_item_detail(request, category, pk):
    """
    Представление страницы со всей информацией о блюде
    View of a page with all the information about the dish
    """
    config = CATEGORY_CONFIG.get(category)
    if not config:
        return render(request, '404.html', status=404)

    item = get_object_or_404(config['model'], pk=pk)
    if config['topping_model']:
        topping_model = config['topping_model']
        toppings = topping_model.objects.filter(item=item).select_related(
            'topping')
    else:
        toppings = []

    context = {
        'item': item,
        'toppings': toppings,
        'category': category,
        'title': f'{item.name} | Animatronic Pizzeria',
    }
    return render(request, 'menu/item_detail.html', context)

templates/menu/categories.html
{% extends "base.html" %}
{% load static %}

{% block title %}Категории меню{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/menu.css' %}">
{% endblock %}

{% block content %}
<div class="menu-container">
    <h1>Меню Animatronic Pizzeria</h1>

    <div class="divider"></div>

    <div class="item-grid">
        {% for category in categories %}
        <a href="{% url 'menu:items' category.url %}" class="category-card">
            <div class="category-icon">{{ category.icon }}</div>
            <h2>{{ category.name }}</h2>
            <p>
                {{ category.count }}
                {% if category.count == 1 %}
                    позиция
                {% elif category.count >= 2 and category.count <= 4 %}
                    позиции
                {% else %}
                    позиций
                {% endif %}
            </p>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/menu/item_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ item.name }}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/menu.css' %}">
{% endblock %}

{% block content %}
<div class="menu-container item-detail">
    <div class="item-header">
        <h1>{{ item.name }}</h1>
        <p class="item-price-detail">{{ item.price }} ₽</p>
    </div>

    <div class="divider"></div>

    <div class="item-content">
        <div class="item-image-container">
            {% if item.image %}
            <img src="{{ item.image.url }}" alt="{{ item.name }}"
                 class="main-image">
            {% else %}
            <img src="{% static 'media/menu/image_missing.png' %}"
                 alt="{{ item.name }}" class="main-image">
            {% endif %}
        </div>

        <div class="item-details">
            <p class="item-description">{{ item.description }}</p>
            <div class="nutrition-info">
                <h3>Пищевая ценность:</h3>
                <ul>
                    <li>Калории: {{ item.calories }} ккал.</li>
                    <li>Белки: {{ item.proteins }} г.</li>
                    <li>Жиры: {{ item.fats }} г.</li>
                    <li>Углеводы: {{ item.carbohydrates }} г.</li>
                    <li>Вес: {{ item.weight }} г.</li>
                </ul>
            </div>

            <div class="toppings-section">
                {% if toppings %}
                <h3>Дополнительные топпинги:</h3>
                <div class="toppings-grid">
                    {% for topping in toppings %}
                    <div class="topping-card">
                        <span class="topping-name">
                            {{ topping.topping.name }}
                        </span>
                        <span class="topping-price">
                            + {{ topping.topping.price_extra }} ₽
                        </span>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <h3>Все топпинги для блюда украли аниматроники</h3>
                {% endif %}
            </div>
        </div>
    </div>
    <a href="{% url 'menu:items' category %}" class="back-button">
        Вернуться к выбору
    </a>
</div>
{% endblock %}

templates/menu/items.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ category_name }}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/menu.css' %}">
{% endblock %}

{% block content %}
<div class="menu-container">
    <a href="{% url 'menu:categories' %}" class="back-button">
        Все категории
    </a>
    <h1>{{ category_name }}</h1>

    <div class="divider"></div>

    <div class="item-grid">
        {% for item in items %}
        <div class="item-card">
            <a href="{% url 'menu:item_detail' category item.pk %}">
                <div class="menu-item-image-container">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" alt="{{ item.name }}"
                         class="item-image">
                    {% else %}
                    <img src="{% static 'media/menu/image_missing.png' %}"
                         alt="{{ item.name }}" class="item-image">
                    {% endif %}
                </div>
                <div class="item-info">
                    <h2 class="item-title">{{ item.name }}</h2>
                    <p class="item-description">
                        {{ item.description|truncatechars:100 }}
                    </p>
                    <p class="item-price">Цена: {{ item.price }} ₽</p>
                    <p class="item-button">Подробнее</p>
                </div>
            </a>
        </div>
        {% empty %}
        <div class="no-items">
            <p>
                В этой категории пока нет блюд. Возможно, аниматроники
                всё съели...
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}